{
 "title": "OpenTelemetry ServiceGraph Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   {
    "name": "workload",
    "label": "workload",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   { "name": "port", "label": "server port", "query": { "query": "label_values(server_port)" } }
  ]
 },
 "panels": [
  {
   "title": "Service Map ☸️",
   "type": "nodeGraph",
   "gridPos": { "h": 24, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (id, mainStat, source, target) (\n  label_replace(\n    label_replace(\n      label_replace(\n        traces_service_graph_request_total, \"source\", \"$1\", \"client\", \"(.*)\"),\n                                            \"target\", \"$1\", \"server\", \"(.*)\"),\n                                            \"mainStat\", \"1\", \"failed\", \".*\")\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (id, title, arc__color) (\n  label_replace(\n    label_replace(\n      label_replace(\n        traces_service_graph_request_total, \"title\", \"$1\", \"client\", \"(.*)\"),\n                                            \"id\", \"$1\", \"title\", \"(.*)\"),\n                                            \"arc__color\", \"1\", \"failed\", \".*\")\n  or\n  label_replace(\n    label_replace(\n      label_replace(\n        traces_service_graph_request_total, \"title\", \"$1\", \"server\", \"(.*)\"),\n                                            \"id\", \"$1\", \"title\", \"(.*)\"),\n                                            \"arc__color\", \"1\", \"failed\", \".*\")\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Ports",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (server_port) (increase((caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\"} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\"})[$__range:$__interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \">\n<div style=\"text-align: center\">\n<p align=\"center\">\n  <img src=\"https://raw.githubusercontent.com/groundcover-com/caretta/main/images/logo.svg\" width=\"75%\" alt=\"caretta\" title=\"caretta\" />\n  <h4>by <a href=\"https://www.groundcover.com\">groundcover</h4>\n\n  \n  [![slack](https://img.shields.io/badge/slack-groundcover-yellowgreen.svg?logo=slack)](http://www.groundcover.com/join-slack)\n  \n</div>\n</p>\n</div>\n</td>\n</table>\n"
   }
  },
  {
   "title": "Top Throughput Workloads",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8, sum by (client_name) ((rate(caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\"}[$__range:$__interval]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Throughput Connections",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7, sum by (client_name, server_name) ( rate( (caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"(node|external)\",} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\", server_kind!~\"(node|external)\"})[$__range:$__interval]) ) )",
     "legendFormat": "{{client_name}} ⮂ {{server_name}}"
    }
   ]
  }
 ]
}